server:
   port: 8080
spring:
  datasource:
      drive-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sys?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: kjsh22887!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    general-ddl: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: validate
security:
   oauth:
      authorization:
         check-token-access: isAuthenticated()
   oauth2:
      jwt:
         signkey: 123@#$
## security: JWT 블록 - isAuthenticated() 인증되었는지 여부
##---

## server:
##   port: 8081
##spring:
##   h2:
##      console:
##      enabled: true
##      settings:
##        web-allow-others: true
##   datasource:
##      url: jdbc:h2:tcp://localhost/~/test
##      driver-class-name: org.h2.Driver
##      username: sa
##jpa:
##   database-platform: database-platform=org.hibernate.dialect.MySQL5Dialect
##   properties.hibernate.hbm2ddl.auto: update
##   showSql: true